version: "3.8"

services:
  web:
      build: .
      ports:
        - "8000:8000"
      command: >
        sh -c "cd students_manager && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code